spring:
    application:
        name: BibilophilesBazar
    datasource:
        url: jdbc:mysql://localhost:3306/bibilophilesbazar
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope: email, profile
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        user-name-attribute: sub

# jwt
app:
    jwt:
        secret: ${JWT_SECRET}
        expiration: 900000 # 15 minutes
        refresh-expiration: 604800000 # 7 days
        frontend-url: http://localhost:5174

# s3 buckent
aws:
    region: ${AWS_REGION}

    accessKey: ${AWS_ACCESS_KEY_ID}
    secret: ${AWS_SECRET_ACCESS_KEY}
    s3:
        bucket: ${AWS_S3_BUCKET}

# grafana and prometheus
management:
    endpoint:
        prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health, info, prometheus

logging:
    level:
        com.backend.infrastructure.security.JWTAuthFilter: DEBUG
        org.springframework.security: DEBUG
        com.backend.infrastructure.persistence.repositoryImplementation.UserRepositoryImpl: DEBUG
        com.backend.presentation.controller.BookCatalogController: DEBUG
        com.backend.application.service: DEBUG
        com.backend.infrastructure.persistence.repositoryImplementation.CategoryRepositoryImpl: DEBUG
server:
    port: ${PORT:2007}
